paths:
  /v1/api/products/:
    get:
      summary: Obtiene todos los productos paginados
      tags:
        - Products
      responses:
        '200':
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        '500':
          description: Error interno del servidor
    post:
      summary: Crea un nuevo producto. Esta ruta requiere que el usuario tenga una sesión activa.
      tags:
        - Products
      security:
        - isActiveSession: true # Verifica si la sesión del usuario está activa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#components/requestBodies/createProduct'
      responses:
        '201':
          description: Nuevo producto guardado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        '400':
          description: No se proporcionó un producto válido
        '203':
          description: Faltan campos requeridos
        '500':
          description: Error interno del servidor
  /v1/api/products/{pid}:
    get:
      summary: Obtiene un producto a partir de su id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto que desea solicitar
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        '404':
          description: Producto no encontrado - probablemente error en el id o producto eliminado de la base de datos
        '500':
          description: Error interno del servidor
    patch:
      summary: Actualiza un producto a partir de su id. Esta ruta requiere que el usuario tenga una sesión activa. Además, verifica si el usuario es propietario del producto. ('admin' modifica cualquier producto, 'user' modifica sólo sus productos)
      tags:
        - Products
      security:
        - isActiveSession: true # Verifica si la sesión del usuario está activa
        - checkProductOwner: true # Verifica si el usuario es propietario del producto
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto que desea actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              $ref: '#components/requestBodies/updateProduct'
        '200':
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        '500':
          description: Error interno del servidor
    delete:
      summary: Elimina un producto a partir de su id. Esta ruta requiere que el usuario tenga una sesión activa. Además, verifica si el usuario es propietario del producto. ('admin' elimina cualquier producto, 'user' elimina sólo sus productos)
      tags:
        - Products
      security:
        - isActiveSession: true # Verifica si la sesión del usuario está activa
        - checkProductOwner: true # Verifica si el usuario es propietario del producto
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto que desea eliminar
      responses:
        '200':
          description: El producto ha sido eliminado correctamente
        '404':
          description: Producto no encontrado, probablemente error en el id
        '500':
          description: Error interno del servidor

components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: String
          description: Id autogenerado por mongoDB
        title:
          type: String
          description: Nombre del producto
          required: true
        description:
          type: String
          description: Descripción del producto
          required: true
        trademark:
          type: String
          description: Marca del producto
          required: true
        price:
          type: Number
          description: Precio del producto
          required: true
          min: 0.0
          max: Number.MAX_VALUE
        status:
          type: Boolean
          description: Indica si el producto se encuentra disponible, puede modificarse en base a la falta de stock o que esté pausado por algún motivo
          default: true
          required: true
        stock:
          type: Number
          description: Cantidad de stock del producto
          required: true
        category:
          type: String
          description: Categoría del producto
          required: true
        condition:
          type: String
          description: Indica si es un producto nuevo o usado
          enum: ['nuevo', 'usado']
        score:
          type: Number
          description: Es la valoración que tiene el producto por parte de los compradores
          enum: [0, 1, 2, 3, 4, 5]
          default: 0
        opinions:
          type: Array
          description: Opiniones sobre el producto por parte de los compradores
          required: false
        thumbnails:
          type: Array
          description: Imágenes del producto
          name:
            type: String
          data:
            type: Buffer
          required: false
        deliveryMethod:
          type: Array
          description: Array de Strings que indica los tipos de entrega disponible del producto
          enum: ['freeShipping', 'costShipping', 'homePickup']
          default: 'homePickup'
        lastModifyDate:
          type: Date
          description: Fecha de última modificación del producto
          required: true
          default: new Date()
        owner:
          type: String
          required: true
      example:
        _id: '64e3e242f5ea3a37f8190375'
        title: Monitor Led
        description: 17inch FHD 1920 x 1080
        trademark: Samsung
        price: 150000
        status: true
        stock: 25
        category: screen
        condition: nuevo
        score: 3
        opinions:
          [
            'lorem ipsum dolor sit amet',
            'lorem ipsum dolor sit amet',
            'lorem ipsum dolor sit amet',
          ]
        thumbnails:
          [
            { name: 'monitor_img.png', data: Buffer },
            { name: 'monitor_dim.png', data: Buffer },
          ]

        deliveryMethod: ['freeShipping', 'costShipping', 'homePickup']
        lastModifyDate: 2023-08-15T14:46:21.999+00:00
        owner: '64df91cecaf5d075245d1d68'
  requestBodies:
    createProduct:
      type: Object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        trademark:
          type: String
          description: Marca del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Cantidad de stock del producto
        category:
          type: String,
          description: Categoría del producto
        condition:
          type: String
          description: Indica si es un producto nuevo o usado
        thumbnails:
          type: Array
          description: Imágenes del producto
        deliveryMethod:
          type: Array
          description: Array de Strings que indica los tipos de entrega disponible del producto
      example:
        title: Calculadora científica
        description: Ecal auto power off
        trademark: Casio
        price: 20000
        stock: 2
        category: calculadoras
        condition: usado
        thumbnails: [{ name: 'calculadora.png', data: Buffer }]
        deliveryMethod: ['costShipping', 'homePickup']
    updateProduct:
      type: Object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        trademark:
          type: String
          description: Marca del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Cantidad de stock del producto
        category:
          type: String,
          description: Categoría del producto
        condition:
          type: String
          description: Indica si es un producto nuevo o usado
        thumbnails:
          type: Array
          description: Imágenes del producto
        deliveryMethod:
          type: Array
          description: Array de Strings que indica los tipos de entrega disponible del producto
      example:
        title: Monitor Led curvo
        price: 200000
        stock: 32
